### ISSUE TITLE
SMH -_- Have some respect for orginal coders  

### ISSUE THREAD

**Issue by Hail2Hydra** [amykr777/PhishDetect#1]
https://github.com/florienzh4x/GooDorker

1000% Stole Code and just added your name to it Project was created 3 years ago All you did was change the name to your OWN 
theres nthing you can deny proof if all right there sooo....................
Come on now... Give respect to actual coder by either removing tool or actually giving credits inside python script  instead oc claiming you tool the time to code because thats wrong and you know it 

(LIKE THIS ) 

#!/bin/bash
# Coded by Aman Kumar
# https://github.com/amykr777
# Project for GPCSSI 2021

---------------------Change ----------------------------------

#!/bin/bash
# Coded by Monkey B Luffy
# https://github.com/florienzh4x
# Special Thanks for Rinto AR

--------------------------------------------

  |o_o |	
    |:_/ |   ========= Google Dorker ============
   //   \ \  ====== Code by Aman Kumar ==========
  (|     | ) ==== Project for GPCSSI 2021 =======
 /\'\_   _/`\
 \___)=(___/

----------Change to------------------------

 .--.
    |o_o |	
    |:_/ |   ========= Google Dorker =========
   //   \ \  ====== Code by Florienzh4x ======
  (|     | ) ====== Thanks to Rinto AR =======
 /\'\_   _/`\
 \___)=(___/

**Comment by amykr777** [comment]
I haven't completed the project, I would have given credit once the project was completed

**Comment by Hail2Hydra** [comment]
how does noy having the project complete affect the fact you changed all the names... to igve yourself credit

**Comment by Hail2Hydra** [comment]
thats BS And you know it ..but ill give you a chance ill be around thread making sure eventually you give respect the coder that worked hard deserved he.......  he is too now watching and waiting for the changes to be made
